apiVersion: v1
kind: Service
metadata:
  name: lb-frontend
  labels:
    app: frontend
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTPS","http":"HTTP"}'  # HTTPS (TLS) between load balancer and application
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
  selector:
    app: frontend
