apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "k8app-chart.fullname" . }}-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "k8app-chart.fullname" . }}-backend
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60