apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "k8app-chart.fullname" . }}-internal-ca-issuer
spec:
  ca:
    secretName: {{ include "k8app-chart.fullname" . }}-ca-tls-secret