apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8app-chart.fullname" . }}-postgres-volume-claim
  labels:
    app: postgres
  {{- include "k8app-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.postgresVolumeClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.postgresVolumeClaim.storageClass | quote }}