apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8app-chart.fullname" . }}-postgres-secret
  labels:
  {{- include "k8app-chart.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ required "postgresSecret.postgresPassword is required" .Values.postgresSecret.postgresPassword
    | b64enc | quote }}
type: Opaque