apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8app-chart.fullname" . }}-backend
  labels:
  {{- include "k8app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.type }}
  selector:
    app: k8app-backend
  {{- include "k8app-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backend.ports | toYaml | nindent 2 -}}