apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8app-chart.fullname" . }}-backend-config
  labels:
    app: k8app-backend
  {{- include "k8app-chart.labels" . | nindent 4 }}
data:
  BACKEND_CORS_ORIGINS: {{ .Values.backendConfig.backendCorsOrigins | quote }}
  POSTGRES_DB: {{ .Values.backendConfig.postgresDb | quote }}
  POSTGRES_PASSWORD: {{ .Values.backendConfig.postgresPassword | quote }}
  POSTGRES_SERVER: {{ .Values.backendConfig.postgresServer | quote }}
  POSTGRES_USER: {{ .Values.backendConfig.postgresUser | quote }}
  PROJECT_NAME: {{ .Values.backendConfig.projectName | quote }}
  SECRET_KEY: {{ .Values.backendConfig.secretKey | quote }}
  SERVER_HOST: {{ .Values.backendConfig.serverHost | quote }}
  SERVER_NAME: {{ .Values.backendConfig.serverName | quote }}