apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8app-chart.fullname" . }}-ca-tls-secret
  namespace: cert-manager
data:
  tls.crt: {{ .Values.certManagerConfig.base64Crt }}
  tls.key: {{ .Values.certManagerConfig.base64Key }}
