apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8app-chart.fullname" . }}-frontend-config
  labels:
    app: k8app-frontend
  {{- include "k8app-chart.labels" . | nindent 4 }}
data:
  REACT_APP_BACKEND_BASE_URI: {{ .Values.frontendConfig.reactAppBackendBaseUri
    | quote }}