apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8app-chart.fullname" . }}-postgres-config
  labels:
    app: postgres
  {{- include "k8app-chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgresConfig.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.postgresConfig.postgresUser | quote }}