apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "k8app-chart.fullname" . }}-postgres-volume
  labels:
    app: postgres
    type: local
  {{- include "k8app-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/postgresql
  storageClassName: manual