apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: default
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services", "secrets", "configmaps"]
  verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]
