apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: app
  POSTGRES_USER: admin
  PGDATA: /var/lib/postgresql/data/pgdata
  # POSTGRES_PASSWORD: pass
