apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8app-backend
spec:
  replicas: 2 # One pod will be killed when there is no load by HPA
  selector:
    matchLabels:
      app: k8app-backend
  strategy:
    type: Recreate # All existing Pods are killed before new ones are created
  template:
    metadata:
      labels:
        app: k8app-backend
        role: backend
    spec:
      containers:
        - name: k8app-backend
          image: dangg/k8app-backend-image
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          envFrom:
            - configMapRef:
                name: k8app-backend-config
            - configMapRef:
                name: postgres-config # populate db-specific values (needed to keep one source of truth)
            - secretRef:
                name: postgres-secret # populate db-specific secrets (needed to keep one source of truth)
          resources:
            limits:
              cpu: 0.5
            requests:
              cpu: 0.25 # gives 1/2 of the limit