apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8app-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8app-frontend
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60