apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend
spec:
  replicas: 2 # One pod will be killed when there is no load by HPA
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
        role: backend
    spec:
      containers:
        - name: backend-container
          image: kotonium/k8app-backend-image:1.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
            - configMapRef:
                name: postgres-config # populate db-specific values (needed to keep one source of truth)
            - secretRef:
                name: postgres-secret # populate db-specific secrets (needed to keep one source of truth)
          resources:
            limits:
              cpu: "0.25"
#              memory: "128Mi"
            requests:
              cpu: "0.15" # gives 1/2 of the limit
#              memory: "64Mi"