kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim  # Sets name of PVC
  labels:
    app: postgres
spec:
  storageClassName: ssd-postgres-rwo
  accessModes:
    - ReadWriteOnce  # Sets read and write access
  resources:
    requests:
      storage: 2Gi  # Sets volume size