version: '3.7'
services:

  db:
    image: postgres:15
    container_name: k8app-db
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    container_name: k8app-backend
    depends_on:
      - db
    ports:
      - "8080:80" # BE is mapped to 8080 so we can run FE on :80
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    container_name: k8app-frontend
    depends_on:
      - backend
    ports:
      - '5000:80'
    env_file:
      - .env
#    environment: # Will also work
#      - "REACT_APP_BACKEND_BASE_URI=production.example.com"
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile

volumes:
  app-db-data:
    driver: local